---
name: "((deployment_name))"
releases:
- name: osb-java
  version: latest
- name: routing
  version: latest
- sha1: 29ee5338c78f0afad8b192e5b25c2b78725c3820
  url: https://s3.eu-central-1.amazonaws.com/lbaas-boshrelease-pipeline-ev/osb-bosh-haproxy-0.0.3.tgz
  name: osb-bosh-haproxy
  version: 0.0.3
update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: service-broker
  azs:
  - z1
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: application-runtime
    release: osb-java
  - name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: cf
  properties:
    service-broker:
      name: "((name))"
      application: "((application_name))"
      port: 8080
      profile: "((application_profile))"
    cloud-config:
      endpoint: https://config-server.cf.dev.eu-de-central.msh.host
      username: admin
      password: cloudfoundry
    route_registrar:
      routes:
      - name: "((application_name))"
        registration_interval: 20s
        port: 8080
        tags:
          component: "((application_name))"
          env: development
        uris:
        - "((application_hostname))"
