---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt
name: haproxy-letsencrypt

releases:
- name: osb-haproxy
  version: latest
- name: osb-monitoring
  version: latest
- name: cron
  version: 1.1.3
  url:  https://github.com/cloudfoundry-community/cron-boshrelease/releases/download/v1.1.3/cron-1.1.3.tgz

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

# Commented properties for local development
instance_groups:
- name: haproxy
  instances: 1
  vm_type: default
  stemcell: default
#  azs:
#  - z1
  networks:
# - name: default
  - name: service-1
  - name: floating
  jobs:
  - name: haproxy
    release: osb-haproxy
  - name: haproxy_exporter
    release: osb-monitoring
  - name: cron
    release: cron
    properties:
      cron:
        entries:
        - command: /var/vcap/jobs/haproxy/bin/generate_certs 9785 >> /var/vcap/sys/log/cron/generate_certs.log 2>> /var/vcap/sys/log/cron/generate_certs.err.log
          day: '*'
          hour: '1'
          lock: /var/vcap/sys/run/cron/generate_certs.lock
          minute: '0'
          month: '*'
          user: root
          wday: '*'
  properties:
    haproxy:
      binding_ip: 0.0.0.0
      stats_enable: true
      stats_user: admin
      stats_password: admin
      backend_servers:
      - 10.0.8.12
      - 10.0.16.11
      tcp:
      - name: ssh
        balance: roundrobin
        port: 2222
        backend_port: 2222
        check: "check"
        backend_servers:
        - 10.0.8.13
        - 10.0.16.12
