---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt
name: haproxy

releases:
- name: osb-haproxy
  version: latest
- name: osb-monitoring
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: haproxy
  instances: 1
  vm_type: default
  stemcell: default
  azs: [z1, z2]
  networks:
  - name: default
  jobs:
  - name: haproxy
    release: osb-haproxy
  - name: node_exporter
    release: osb-monitoring
  - name: haproxy_exporter
    release: osb-monitoring
  properties:
    haproxy:
      binding_ip: 0.0.0.0
      backend_port: 443
      stats_enable: true
      stats_user: admin
      stats_password: admin
      letsencrypt:
        enabled: true
        email: ops@meshcloud.io
        domains:
        - lbaas-le-demo.meshcloud.io
